services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: sqlserver_db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=animeSenha123
    ports:
      - "1433:1433"
    

  myapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: AnimeApi
    environment:
      - ANIMES_BANCO=Server=sqlserver,1433;Database=animesdb;User ID=sa;Password=animeSenha123;
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:8080"
    depends_on:
      - sqlserver
