services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=#animes123
    ports:
      - "1433:1433"

  myapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: myapi
    environment:
      - ANIMES_BANCO=Server=sqlserver;Database=AnimesDb;User Id=sa;Password=#animes123;
    ports:
      - "80:80"
    depends_on:
      - sqlserver
